### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by cristianofromagio** [elbitdigital/ferreira#1]
## Meta: 
[Descrição de uma linha] 

## Tarefas: 
- [x] Diretório do projeto no Github
- [x] Importação do diretório BASE
- [ ] Arquivo de logo (SVG)
- [ ] Lib. de ícones (Fontello)
- [x] Projeto no Typekit
- [x] Incorporação de configuração do Typekit no index
- [x] Projeto no Firebase
- [x] Compartilhar projeto no Firebase com time
- [x] Configurações de deploy do Firebase (.firebaserc)
- [ ] Configuração do domínio (DNS)
- [ ] Configuração de emails
- [ ] Projeto no Analytics
- [ ] Confirmar propriedade no Google Search Console
- [x] Definição do nome de projeto (GulpFile)
- [x] Definição do nome de projeto (_.js)
- [x] Definição do nome de projeto (_.css)
- [x] Configuração do arquivo package.json
- [x] Construção dos arquivos de distribuição
- [x] Definição de dependências de desenvolvimento (npm)

**Comment by dbarjs** [comment]
`<script>
  (function(d) {
    var config = {
      kitId: 'hyi0dvn',
      scriptTimeout: 3000,
      async: true
    },
    h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
  })(document);
</script>`

**Comment by dbarjs** [comment]
`zcf1tth`
